ci: move away from fly.io
teknologi-umum/graphene pull request #121
Opened 2022-11-27 04:32 UTC by elianiva

2022-11-27 04:46 UTC, aldy505 requested changes

2022-11-27 04:46 UTC, aldy505 commented on .github/workflows/ci.yml
> +          'ssh pesto "cd ${{ secrets.SSH_WORKDIR }}/graphene && git pull" '
```suggestion
          'ssh graphene "cd ${{ secrets.SSH_WORKDIR }}/graphene && git pull" '
```

2022-11-27 04:46 UTC, aldy505 commented on .github/workflows/ci.yml
> +          "ssh pesto 'echo ${{ secrets.SSH_PASSWORD }} | sudo -S bash -c '\"'cd ${{ secrets.SSH_WORKDIR }}/graphene &&
```suggestion
          "ssh graphene 'echo ${{ secrets.SSH_PASSWORD }} | sudo -S bash -c '\"'cd ${{ secrets.SSH_WORKDIR }}/graphene &&
```

2022-11-27 04:46 UTC, aldy505 commented on .github/workflows/ci.yml
> +          "ssh pesto 'echo ${{ secrets.SSH_PASSWORD }} | sudo -S bash -c '\"'docker container prune -f &&
```suggestion
          "ssh graphene 'echo ${{ secrets.SSH_PASSWORD }} | sudo -S bash -c '\"'docker container prune -f &&
```

2022-11-27 04:46 UTC, aldy505 commented on docker-compose.yml
> +      - "traefik.http.middlewares.graphene-header.headers.accesscontrolmaxage=604800"
kalo di graphenenya udah ada cors middleware, gaperlu nambah lagi disini

2022-11-27 04:46 UTC, aldy505 commented on docker-compose.yml
> +      - "traefik.http.routers.graphene.rule=Host(`graphene.teknologiumum.com`) && (Path(`/`) || PathPrefix(`/api`))"
```suggestion
      - "traefik.http.routers.graphene.rule=Host(`graphene.teknologiumum.com`)"
```

2022-11-27 04:46 UTC, aldy505 commented on docker-compose.yml
> +      replicas: 3
kenapa harus 3 replica? kalo emang mau load banyak, 2 aja udah cukup.

2022-11-27 04:46 UTC, aldy505 commented on docker-compose.yml
> +  ENVIRONMENT: development
```suggestion
  ENVIRONMENT: production
```

2022-11-27 04:46 UTC, aldy505 commented on docker-compose.yml
> +      PORT: 3000
yakin segini doang?

2022-11-27 09:28 UTC, elianiva commented on docker-compose.yml
> +      replicas: 3
karena copas xixixi

2022-11-27 09:29 UTC, elianiva commented on docker-compose.yml
> +      PORT: 3000
emang itu doang

2022-11-27 12:00 UTC, aldy505 commented on docker-compose.yml
> +      PORT: 3000
yakin nggak butuh `SENTRY_DSN`?

2022-11-29 05:16 UTC, elianiva commented
MANTEP, CI-NYA JALAN

2022-11-29 05:17 UTC, elianiva commented on docker-compose.yml
> +      PORT: 3000
ngga pegang akun sentry

2022-12-01 13:37 UTC, aldy505 commented on docker-compose.yml
> +      PORT: 3000
sekarang pegang

2022-12-31 02:50 UTC, merged